Gd 122
IT-Siberians/EmailSenderMicroservice pull request #5
Opened 2024-08-23 13:36 UTC by Barmalej24

2024-08-24 04:12 UTC, Barmalej24 commented
fixed naming

2024-08-25 20:03 UTC, m-a-ilnitsky approved these changes
Есть мелкие замечания.
В целом, очень круто.

2024-08-25 20:03 UTC, m-a-ilnitsky commented on EmailSenderMicroservice.Application/Model/MessageAddModel.cs
> +    public record MessageAddModel(
Здесь должен быть другой порядок слов: AddMessageModel, т.к. здесь имя DTO соответствует имени метода в котором используется

2024-08-25 20:03 UTC, m-a-ilnitsky commented on EmailSenderMicroservice.Application/Services/Abstraction/Base/IService.cs
> +    public interface IService<TEntity, TEntityAdd, TKey> where TEntity : class where TEntityAdd : class where TKey : struct
Здесь лучше каждое where писать с новой строки, это будет лучше читаться

2024-08-25 20:03 UTC, m-a-ilnitsky commented on EmailSenderMicroservice.Application/Model/SettingAddModel.cs
> +    public record SettingAddModel(
Здесь видимо тоже имя DTO должно начинаться с глагола, если оно отражает имя метода/запроса в котором DTO используется

2024-08-25 20:03 UTC, m-a-ilnitsky commented on EmailSenderMicroservice.Application/Services/SenderService.cs
> +        private readonly IMessageService _message;
_setting, _message - в эти имена лучше добавить слово Service.
Сейчас имена непонятные

2024-08-25 20:03 UTC, m-a-ilnitsky commented on EmailSenderMicroservice.Application/Services/SenderService.cs
> +            };
Можно использовать инициализатор, если это покажется красивее:
var message = new MimeMessage
{
    Subject = subject,
    Body = new TextPart(isHtml ? "html" : "plain")
    {
        Text = text
    }
};
message.From.Add(new MailboxAddress(fromName, settingNow.Login));
message.To.Add(new MailboxAddress(toName, toEmail))

2024-08-25 20:03 UTC, m-a-ilnitsky commented on EmailSenderMicroservice.DataAccess/EmailSenderMicroserviceDbContext.cs
> +        public DbSet<Setting> Settings { get; set; }
Свойства лучше объявить выше методов

2024-08-25 20:03 UTC, m-a-ilnitsky commented on EmailSenderMicroservice.DataAccess/Repossitory/SettingRepository.cs
> +        public async Task<Setting?> GetAsync(CancellationToken cancellationToken)
Возможно лучше назвать GetLastAsync

2024-08-25 20:03 UTC, m-a-ilnitsky commented on EmailSenderMicroservice.DataAccess/Repossitory/SettingRepository.cs
> +namespace EmailSenderMicroservice.DataAccess.Repossitory
Опечатка в слове Repossitory.
И здесь должно быть множественное число

2024-08-25 20:03 UTC, m-a-ilnitsky commented on EmailSenderMicroservice.DataAccess/Repossitory/SettingRepository.cs
> +                );
Всем .SetProperty нужно добавить отступ, чтобы было видно, что это вложенная цепочка

2024-08-25 20:03 UTC, m-a-ilnitsky commented on EmailSenderMicroservice.Domain/Entities/Base/IEntity.cs
> +        DateTime CreatedDate { get; }
Имя лучше поправить, сейчас получается "созданная дата"

2024-08-25 20:03 UTC, m-a-ilnitsky commented on EmailSenderMicroservice.Domain/Entities/Message.cs
> +        public DateTime CreatedDate { get; }
Аналогично

2024-08-26 15:53 UTC, oleggolen commented on EmailSenderMicroservice.Application/Model/MessageAddModel.cs
> +    public record MessageAddModel(
В принципе так тоже можно, но по правилам английского языка да

2024-08-26 16:55 UTC, oleggolen requested changes
Уже практически идеальный код, надо исправить несколько небольших опечаток, типы исключений и сделать эмуляцию брокера сообщений или начать подключать брокер сообщений, чтобы была видна идея

2024-08-26 16:55 UTC, oleggolen commented on EmailSenderMicroservice.Application/Model/SettingAddModel.cs
> +    public record SettingAddModel(
Тоже амое про английкий язык

2024-08-26 16:55 UTC, oleggolen commented on EmailSenderMicroservice.Application/Model/SettingModel.cs
> +﻿namespace EmailSenderMicroservice.Application.Model
Я бы ещё модельки Message и Setting сгруппировал бы в отдельные папки, да и информацию аутентификации и адресную информацию группировал во внутренние отдельные объекты

2024-08-26 16:55 UTC, oleggolen commented on EmailSenderMicroservice.Application/Services/Abstraction/Base/IService.cs
> +    public interface IService<TEntity, TEntityAdd, TKey> where TEntity : class where TEntityAdd : class where TKey : struct
Даже на маленьком экране ноутбука читается нормально, проблема возникает тогда, когда это за границы экрана вылезать начинает

2024-08-26 16:55 UTC, oleggolen commented on EmailSenderMicroservice.Application/Services/Abstraction/ISettingService.cs
> +        Task<SettingModel?> GetAsync();
Лучше назвать метод как-то попонятнее типо GetCurrentAsync или GetLastAsync а то совсем непонятно что мы получаем так ещё и без параметров

2024-08-26 16:55 UTC, oleggolen commented on EmailSenderMicroservice.Application/Services/ConsumerBackgroundService.cs
> +    public class ConsumerBackgroundService : BackgroundService
Здесь предполагается брокер сообщений или для чего этот сервис вообще?

2024-08-26 16:55 UTC, oleggolen commented on EmailSenderMicroservice.Application/Services/ConsumerBackgroundService.cs
> +            var test = _sender.SendAsync("vasya", "pophas123@mail.ru", "Важное уведомление", "что-то какой-то текст", true);
Лучше не использовать константы, или получить объект из какого-то временно файкового сервиса, эмулирующего, например, брокер или ещё что-то, выглядит очень странно пока что

2024-08-26 16:55 UTC, oleggolen commented on EmailSenderMicroservice.Application/Services/SenderService.cs
> +        private readonly IMessageService _message;
Согласен

2024-08-26 16:55 UTC, oleggolen commented on EmailSenderMicroservice.Application/Services/SenderService.cs
> +            };
Да, как вариант

2024-08-26 16:55 UTC, oleggolen commented on EmailSenderMicroservice.DataAccess/Repossitory/Abstraction/ISettingRepository.cs
> +        Task<Setting?> GetAsync(CancellationToken cancellationToken);
Тоже самое лучше назвать метод более детально, чтобы из названия было понятно, что именно мы получаем

2024-08-26 16:55 UTC, oleggolen commented on EmailSenderMicroservice.DataAccess/Repossitory/SettingRepository.cs
> +namespace EmailSenderMicroservice.DataAccess.Repossitory
Согласен, но тогда и всю папку так назвать надо

2024-08-26 16:55 UTC, oleggolen commented on EmailSenderMicroservice.Domain/Entities/Base/IEntity.cs
> +        DateTime CreatedDate { get; }
В принципе и так нормально, но лучше CreattionDate

2024-08-26 16:55 UTC, oleggolen commented on EmailSenderMicroservice.Domain/Exception/Setting/SettingGuidEmptyException.cs
> +    {
Лучше использовать ArgumentNullException в качестве базового

2024-08-26 16:55 UTC, oleggolen commented on EmailSenderMicroservice.Domain/Exception/Message/MessageGuidEmptyException.cs
> +    public class MessageGuidEmptyException(string message, string value) : ArgumentException(message, value)
Лучше использовать ArgumentNullException в качестве базового

2024-08-26 16:55 UTC, oleggolen commented on EmailSenderMicroservice.Domain/Exception/Setting/SettingServerAddressLengthException.cs
> +    public class SettingServerAddressLengthException(string message, string value) : ArgumentException(message, value)
Лучше использовать FotmatException в качестве базового

2024-08-26 16:55 UTC, oleggolen commented on EmailSenderMicroservice.Domain/Exception/VoalueObject/EmailInvalidException.cs
> +﻿namespace EmailSenderMicroservice.Domain.Exception.ValueObject
Папку назвать также как пространство имён

2024-08-27 13:18 UTC, m-a-ilnitsky commented on EmailSenderMicroservice.Application/Services/Abstraction/Base/IService.cs
> +    public interface IService<TEntity, TEntityAdd, TKey> where TEntity : class where TEntityAdd : class where TKey : struct
Здесь я имел ввиду что в одной строке казано три отдельных where которые визуально  не сильно выделяются на фоне соседних class и struct.
Это затрудняет чтение даже если вся строка влазит на экран
А если писать каждый where с новой строки то хорошо видно какие ограничения к какому параметру относятся

2024-08-29 13:44 UTC, closed without merging